executable = /lustre/Auger/brais.rocha/spacetime_correlations/jobs/condor/grid_p50/run_grid_p50.sh

output = /lustre/Auger/brais.rocha/spacetime_correlations/logs/condor/grid_p50/grid_p50_$(Process).out
error  = /lustre/Auger/brais.rocha/spacetime_correlations/logs/condor/grid_p50/grid_p50_$(Process).err
log    = /lustre/Auger/brais.rocha/spacetime_correlations/logs/condor/grid_p50/grid_p50_$(Process).log

should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT
+flavour                = "xshort"
arguments               = $(flare_duration) $(flare_intensity) $(seed) $(Process) $(submission_id)
request_memory          = 1G

queue flare_duration, flare_intensity, seed from /lustre/Auger/brais.rocha/spacetime_correlations/jobs/condor/grid_p50/grid_p50_params.txt
